version: "3.5"
services:
  database:
    image: qdrant/qdrant:latest
    container_name: yanfei-data
    ports:
      - 127.0.0.1:2201:6333
    volumes:
      - qdrant:/qdrant/storage
    networks:
      - yanfei
    restart: always

  cache:
    image: redis:7.0
    container_name: yanfei-cache
    ports:
      - 127.0.0.1:2202:6379
    networks:
      - yanfei
    restart: always

volumes:
  qdrant:
    driver: local

networks:
  yanfei:
    name: yanfei
    driver: bridge
